// <auto-generated />
using System;
using GamingPlatformAPI.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingPlatformAPI.Migrations
{
    [DbContext(typeof(GamingDbContext))]
    [Migration("20260201172745_userrr")]
    partial class userrr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingPlatformAPI.models.Affiliate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Affiliates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "affiliate@example.com",
                            Name = "SuperAffiliate",
                            PasswordHash = "hashedpassword"
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            Name = "John Doe",
                            PasswordHash = "hashedpassword"
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.ClickTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateId");

                    b.ToTable("Clicks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffiliateId = 1,
                            IPAddress = "192.168.1.100",
                            Timestamp = new DateTime(2026, 1, 31, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AffiliateId = 1,
                            IPAddress = "192.168.1.101",
                            Timestamp = new DateTime(2026, 1, 31, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Amount = 100.50m,
                            Date = new DateTime(2026, 1, 31, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            Amount = 200.75m,
                            Date = new DateTime(2026, 1, 30, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 1,
                            Amount = 150.00m,
                            Date = new DateTime(2026, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Withdrawals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Amount = 50.00m,
                            RequestDate = new DateTime(2026, 1, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            Amount = 100.00m,
                            RequestDate = new DateTime(2026, 1, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.user", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWagers")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            IsBlocked = false,
                            PasswordHash = "hashedpassword",
                            PhoneNumber = "1234567890",
                            TotalDeposits = 1000.00m,
                            TotalLosses = 100.00m,
                            TotalWagers = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            IsBlocked = false,
                            PasswordHash = "hashedpassword",
                            PhoneNumber = "0987654321",
                            TotalDeposits = 2000.00m,
                            TotalLosses = 200.00m,
                            TotalWagers = 1500.00m
                        });
                });

            modelBuilder.Entity("GamingPlatformAPI.models.ClickTracking", b =>
                {
                    b.HasOne("GamingPlatformAPI.models.Affiliate", "Affiliate")
                        .WithMany("Clicks")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Commission", b =>
                {
                    b.HasOne("GamingPlatformAPI.models.Agent", "Agent")
                        .WithMany("Commissions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Withdrawal", b =>
                {
                    b.HasOne("GamingPlatformAPI.models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GamingPlatformAPI.models.user", b =>
                {
                    b.HasOne("GamingPlatformAPI.models.Agent", "Agent")
                        .WithMany("Users")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Affiliate", b =>
                {
                    b.Navigation("Clicks");
                });

            modelBuilder.Entity("GamingPlatformAPI.models.Agent", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
